#include <iostream> 
using namespace std; 
int main() 
{ 
    try{ 
        try 
         { 
             throw 5; 
         } 
        catch(int n) 
         { 
             cerr<<"exception code "<<n<<endl; 
         } 
        } 
  catch(char msg){ 

       cerr<<"Exception code "<<msg<<endl; 
   } 
  return 0; 
} 
